monitor_task:
  description: >
    Carefully analyze the customer service transcript using the provided service guidelines. 
    Systematically evaluate each interaction against the established standards.
    Identify specific areas where the service deviated from best practices.
    Prepare a detailed, objective report highlighting potential issues, 
    including direct evidence from the transcript to support each observation.
    Make sure you have the guideline and the transcription. You can NOT do your work with both of them.
  expected_output: >
    A comprehensive quality assessment report containing:
    - List of specific guideline violations
    - Detailed explanation of each identified issue
    - Direct quotes supporting the assessment
    - Clear, actionable improvement recommendations
  agent: monitor

operator_task:
  description: >
    Review the Monitor's quality assessment report in detail. 
    Carefully examine each point raised against the full context of the service transcript.
    Provide a thoughtful, professional response that either:
    - Acknowledges the identified issues and explains mitigation strategies
    - Offers a well-reasoned defense with contextual explanations
    - Provide additional context that may modify the initial assessment
    Make sure you have the guideline and the transcription. You can NOT do your work with both of them.
  expected_output: >
    A structured response document including:
    - Point-by-point response to the Monitor's findings
    - Contextual explanations or defenses
    - Supporting evidence from the original transcript
    - Proposed action steps or clarifications
  agent: operator

judge_task:
  description: >
    In the event of a disagreement between the Monitor and Operator, 
    conduct a thorough, impartial review of:
    - The original service transcript
    - Monitor's quality assessment report
    - Operator's response and defense
    
    Analyze the evidence objectively, considering:
    - Alignment with service guidelines
    - Context of the customer interaction
    - Reasonableness of both perspectives

    Make sure you have the guideline and the transcription. You can NOT do your work with both of them.
  expected_output: >
    A definitive assessment document containing:
    - Clear determination of the dispute, but focused on the guidelines, pointing if the operator followed them or not, theres no middle ground, if the operator achieved at least the minimum of the guideline, tell that he followed the guideline but point the errors and how to improve in the analysis.
    - Detailed reasoning behind the decision
    - Supporting evidence from the transcript
    - Objective rationale for the judgment
  agent: judge

supervisor_task:
  description: >
    You was provided with a transcript and a guideline off a customer service interaction

    ###transcript:
    {transcript}

    ###guidelines:
    {guidelines}

    ###task:
    Based on the transcription and guidelines of the customer service provided compile a comprehensive, constructive feedback report based on:
    - Monitor's initial quality assessment
    - Operator's response
    - Judge's decision (if applicable)
    
    Create a professional, actionable document that:
    - Provides clear, balanced insights
    - Highlights both strengths and areas for improvement
    - Offers specific, constructive recommendations
    - Maintains a supportive, development-focused tone

    Your final answer should have a summary of the transcript, the analysis of the guidelines, for example, if the operator followed the guidelines or not and why, the feedback for the operator, and any aditional information that is relevant to the report.
    
    Make sure you passed the guideline and the transcription when necessary, otherwise, workers can NOT do their work with both of them.
  expected_output: >
    Your final answer should have a summary of the transcript, the analysis of the guidelines, for example, if the operator followed the guidelines or not and why, the feedback for the operator, and any aditional information that is relevant to the report.
    A markdown-formatted feedback report including:
    - Executive summary of the assessment
    - Detailed findings from each stage of the review
    - Specific, actionable improvement recommendations
    - Positive acknowledgments of good performance
    - Clear, professional language
    - Use professional business English
  agent: supervisor


reporting_task:
  description: >
    Create a comprehensive quality assessment report using the following inputs:
    - Monitor's initial assessment
    - Operator's response
    - Judge's final decision
    - Service guidelines and transcript

    Follow this exact structure:
    1. Call Transcript Summary
    2. Service Guidelines Analysis (analyze each guideline individually)
    3. Operator Feedback (strengths, improvements, recommendations)
    4. Additional Relevant Information
    5. Conclusion

    Each section must:
    - Include specific examples from the transcript
    - Reference the guidelines directly
    - Maintain professional tone
    - Provide actionable insights
  expected_output: >
    A markdown-formatted report that includes:
    - Detailed summary of the call
    - Analysis of each guideline with compliance status
    - Comprehensive feedback section with specific examples
    - Clear recommendations for improvement
    - Professional conclusion
    - Use professional business English
  agent: reporting_analyst